import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/sidebar'
import LoadAnimation from '@/components/load'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background md:overflow-y-hidden`}>
        <LoadAnimation />
        <Navbar />
        <Sidebar />
        {children}
      </body>
    </html>
  )
}
